### ISSUE TITLE
代码跟里面编译的apk不一样，靠不开源的部分赚钱呢

### ISSUE THREAD

**Issue by yangjinhao0505** [lianglixin/SandVXposed#23]
不开源就不开源，问东西支支吾吾，收费就收费，还不直说

**Comment by lianglixin** [comment]
？

**Comment by dev-xiaosa** [comment]
> 不开源就不开源，问东西支支吾吾，收费就收费，还不直说

找我吧，我有代码。

**Comment by yangjinhao0505** [comment]
多少钱啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月2日(周三) 下午5:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lianglixin/SandVXposed] 代码跟里面编译的apk不一样，靠不开源的部分赚钱呢 (#23)




  
不开源就不开源，问东西支支吾吾，收费就收费，还不直说
  
找我吧，我有代码。

**Comment by github-gsjb** [comment]
> 多少钱啊
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年6月2日(周三) 下午5:55 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [lianglixin/SandVXposed] 代码跟里面编译的apk不一样，靠不开源的部分赚钱呢 (#23) 不开源就不开源，问东西支支吾吾，收费就收费，还不直说 找我吧，我有代码。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你qq多少

**Comment by dev-xiaosa** [comment]
> 多少钱啊
> […](#)

怎么联系？

**Comment by lianglixin** [comment]
强调一次，本项目永久免费，从来没有所谓靠“闭源部分”赚钱，也没有所谓“闭源可赚钱部分”
**注意！此项目由于使用了 VirtualApp 开源版，License 与 VirtualApp 相同，切勿用作商业用途，否则自负法律风险。**
